wiki:
    type: "###EDITION###"    # standalone or farm
    path: "/app/bluespice/w"
    reference: "/app/bin/config/runJobs_settings.php" # LocalSettings.php for DB credentials
runjobs:
    percentage: 50      # Maximum percentage of total jobs. (Per wiki, per cycle)
    maxtime: 20         # Maximum life time of a runJobs.php (Per wiki, per cycle) - Seconds
    cooldown: 3        # Wait time after each cycle - Seconds
    maxforkprocesses: 5 # Maximum number of sub processes that can be spawned for parallel processing
exclude-instances: []
include-instances: []
