environment:
    php: "/usr/bin/php" # Optional, defaults to /usr/bin/php
wiki:
    type: "###EDITION###"    # standalone or farm
    path: "/app/bluespice/w"
database:
    dbserver: "###DB_HOST###" # Optional, defaults to localhost
    dbport: 3306 # Optional, defaults to 3306
    dbname: "###DB_NAME###"
    dbuser: "###DB_USER###"
    dbpassword: "###DB_PASS###"
    dbprefix: "###DB_PREFIX###"
farm: # Whole section is optional
    # Exclude list has priority over include list
    include-instances: []
    exclude-instances: []